import { Printer, FileText, Download } from 'lucide-react';
import { useAppStore } from '@/store/useAppStore';
import { toast } from 'sonner';
import { downloadMarkdown } from '@/utils/exportUtils';

interface ExportControlProps {
  onPrint?: () => void;
  variant?: 'row' | 'col';
}

export default function ExportControl({ onPrint, variant = 'row' }: ExportControlProps) {
  const { projectTitle, tasks } = useAppStore();

  const setModalAlert = useAppStore((state) => state.setModalAlert);

  const checkEmpty = () => {
    if (!tasks || tasks.length === 0) {
      setModalAlert(
        'Start by uploading a video and transcript or pasting text of something you want to learn.',
      );
      return true;
    }
    return false;
  };

  const triggerPrint = () => {
    if (checkEmpty()) return;
    if (onPrint) onPrint();
  };

  const handleCopyMarkdown = async () => {
    if (checkEmpty()) return;

    // Use shared utility logic for consistency (though simpler here for clipboard)
    // We recreate the simple text for clipboard to avoid downloading
    const header = `# ${projectTitle}\nGenerated by Cubit Connect\n\n`;
    const taskText = tasks
      .map((t, i) => {
        return (
          `## ${i + 1}. ${t.task_name}\n${t.description}\n` +
          (t.sub_steps?.map((s) => `- ${typeof s === 'string' ? s : s.text}`).join('\n') || '') +
          '\n'
        );
      })
      .join('\n');

    const fullText = header + taskText;

    try {
      await navigator.clipboard.writeText(fullText);
      toast.success('Markdown Copied', {
        description: 'Report text has been copied to your clipboard.',
      });
      useAppStore.getState().addLog('Markdown Copied to Clipboard');
    } catch {
      toast.error('Copy Failed', { description: 'Could not access clipboard.' });
    }
  };

  const handleDownloadMarkdown = () => {
    if (checkEmpty()) return;
    try {
      downloadMarkdown(tasks, projectTitle);
      toast.success('Download Started', {
        description: 'Your markdown file is ready.',
      });
      useAppStore.getState().addLog('Markdown Downloaded');
    } catch (e) {
      console.error(e);
      toast.error('Download Failed');
    }
  };

  const btnClass =
    variant === 'row'
      ? 'flex items-center gap-2 text-xs text-zinc-600 dark:text-stone-400 hover:text-black dark:hover:text-stone-100 transition-colors'
      : 'w-full justify-start rounded-lg hover:bg-zinc-100 dark:hover:bg-stone-800 mb-2 text-xs px-3 py-3 min-h-[44px] transition-colors font-bold flex items-center gap-2 active:scale-95 text-zinc-600 dark:text-stone-400';

  return (
    <>
      {/* CONTROLS */}
      <div className={variant === 'row' ? 'flex items-center gap-4' : 'flex flex-col gap-1'}>
        <button onClick={triggerPrint} className={btnClass} title="Export PDF">
          <Printer className="w-4 h-4" />
          <span className={variant === 'row' ? 'hidden sm:inline' : ''}>PDF</span>
        </button>

        <button onClick={handleDownloadMarkdown} className={btnClass} title="Download Markdown">
          <Download className="w-4 h-4" />
          <span className={variant === 'row' ? 'hidden sm:inline' : ''}>Download .md</span>
        </button>

        <button onClick={handleCopyMarkdown} className={btnClass} title="Copy Markdown">
          <FileText className="w-4 h-4" />
          <span className={variant === 'row' ? 'hidden sm:inline' : ''}>Copy</span>
        </button>
      </div>
    </>
  );
}
