import { TaskItem, CubitStep } from '@/services/storage';

// Helper to sanitize filenames
export const getSafeFilename = (title: string): string => {
    return title.replace(/[^a-z0-9]+/gi, '_').toLowerCase().replace(/^_+|_+$/g, '') + '.md';
};

// Helper to format time MM:SS
const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
};

export const generateMarkdown = (tasks: TaskItem[], title: string = "Cubit Export"): string => {
    let md = `# ${title}\n\n`;
    md += `Generated by Cubit Connect\n\n---\n\n`;

    tasks.forEach((task) => {
        // H1 Task Name + Timestamp (if valid)
        const timestamp = task.timestamp_seconds > 0 ? ` (${formatTime(task.timestamp_seconds)})` : '';
        md += `## ${task.task_name}${timestamp}\n\n`;

        // Description blockquote
        if (task.description) {
            md += `> ${task.description}\n\n`;
        }

        // Sub-steps (Level 2)
        if (task.sub_steps && task.sub_steps.length > 0) {
            task.sub_steps.forEach((step, sIdx) => {
                const mark = step.isCompleted ? 'x' : ' ';
                md += `${sIdx + 1}. [${mark}] ${step.text}\n`;

                // Micro-steps (Level 3)
                if (step.sub_steps && Array.isArray(step.sub_steps) && step.sub_steps.length > 0) {
                    step.sub_steps.forEach((micro: string | CubitStep) => {
                        // Handle potential String vs Object migration type safety
                        const microText = typeof micro === 'string' ? micro : micro.text;
                        md += `    - ${microText}\n`;
                    });
                }
            });
            md += `\n`; // Spacer between tasks
        }
    });

    return md;
};
